### ISSUE TITLE
ROBOT's OWL to OBO conversion fails

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/ncit-obo#12]
This ROBOT command:

```
java -Xmx4g -jar lib/robot.jar convert --input build/ncit.owl --output build/ncit.obo
```

generates lots of warning like this:

```
WARNING: the axiom is not translated : EquivalentClasses(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C4255> ObjectIntersectionOf(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C4502> ObjectIntersectionOf(ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R114> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36540>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R89> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37241>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R89> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C37242>)) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R105> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C48878>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R105> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C48897>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R108> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36180>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R114> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36455>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R142> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C36162>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R174> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C13224>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R176> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C101053>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R176> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C101054>) ObjectSomeValuesFrom(<http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#R176> <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C71423>)) )
```

then fails with the following message:

```
java.io.IOException: org.semanticweb.owlapi.model.OWLOntologyStorageException: org.obolibrary.oboformat.model.FrameStructureException: multiple def tags not allowed. in frame:Frame(C29670 id( C29670{}[])property_value( P106 Amino Acid, Peptide, or Protein xsd:string{}[])synonym( G Protein-Coupled Receptor 39 EXACT{{http://purl.obolibrary.org/obo/IAO_0000117=NCI} }[])property_value( code C29670 xsd:string{}[])property_value( P106 Receptor xsd:string{}[])name( G Protein-Coupled Receptor 39{}[])property_value( P204 Protein_Encoded_by_Gene|GPR39 Gene xsd:string{}[])property_value( P108 G Protein-Coupled Receptor 39 xsd:string{}[])synonym( Putative G Protein-Coupled Receptor GPR39 EXACT{{http://purl.obolibrary.org/obo/IAO_0000117=NCI} }[])property_value( P204 Protein_Has_Organism_Source|Human xsd:string{}[])synonym( GPR39 EXACT{{http://purl.obolibrary.org/obo/IAO_0000117=NCI} }[])property_value( P310 Retired_Concept xsd:string{}[])property_value( P102 AF034633 xsd:string{}[])is_obsolete( true{}[])def( Widely expressed by human GPR39 Gene (GPCR1 Family), 453-aa 51-kDa 7-transmembrane orphan G Protein-Coupled Receptor 39 exhibits high homology to the growth hormone secretagogue receptor (GHSR). (NCI){{http://purl.obolibrary.org/obo/IAO_0000119=NCI} }[])property_value( P203 Protein_Kind xsd:string{}[])property_value( P93 O43194 xsd:string{}[])property_value( P100 602886 xsd:string{}[])property_value( P204 Protein_Plays_Role_In_Biological_Process|G Protein-Coupled Receptor Signaling xsd:string{}[])property_value( P102 NM_001508 xsd:string{}[])property_value( P200 G Protein-Coupled Receptor xsd:string{}[])property_value( P204 Protein_Has_Biochemical_Function|G Protein-Coupled Receptor xsd:string{}[])def( GPR39 is a single-copy gene, expressed in brain and other peripheral tissues. It encodes G Protein-Coupled Receptor 39, which has high homology to the growth hormone secretagogue receptor (GHSR), a G protein-coupled receptor found in the pituitary gland and brain that is involved in the control of growth hormone release. The ligand-binding and functional properties of GPR39 remain to be determined. (from OMIM and Genomics 1997;46:426-34){{http://purl.obolibrary.org/obo/IAO_0000119=NCI} }[])is_a( C83479{}[]))
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:441)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:414)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:143)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:48)
Caused by: org.semanticweb.owlapi.model.OWLOntologyStorageException: org.obolibrary.oboformat.model.FrameStructureException: multiple def tags not allowed. in frame:Frame(C29670 id( C29670{}[])property_value( P106 Amino Acid, Peptide, or Protein xsd:string{}[])synonym( G Protein-Coupled Receptor 39 EXACT{{http://purl.obolibrary.org/obo/IAO_0000117=NCI} }[])property_value( code C29670 xsd:string{}[])property_value( P106 Receptor xsd:string{}[])name( G Protein-Coupled Receptor 39{}[])property_value( P204 Protein_Encoded_by_Gene|GPR39 Gene xsd:string{}[])property_value( P108 G Protein-Coupled Receptor 39 xsd:string{}[])synonym( Putative G Protein-Coupled Receptor GPR39 EXACT{{http://purl.obolibrary.org/obo/IAO_0000117=NCI} }[])property_value( P204 Protein_Has_Organism_Source|Human xsd:string{}[])synonym( GPR39 EXACT{{http://purl.obolibrary.org/obo/IAO_0000117=NCI} }[])property_value( P310 Retired_Concept xsd:string{}[])property_value( P102 AF034633 xsd:string{}[])is_obsolete( true{}[])def( Widely expressed by human GPR39 Gene (GPCR1 Family), 453-aa 51-kDa 7-transmembrane orphan G Protein-Coupled Receptor 39 exhibits high homology to the growth hormone secretagogue receptor (GHSR). (NCI){{http://purl.obolibrary.org/obo/IAO_0000119=NCI} }[])property_value( P203 Protein_Kind xsd:string{}[])property_value( P93 O43194 xsd:string{}[])property_value( P100 602886 xsd:string{}[])property_value( P204 Protein_Plays_Role_In_Biological_Process|G Protein-Coupled Receptor Signaling xsd:string{}[])property_value( P102 NM_001508 xsd:string{}[])property_value( P200 G Protein-Coupled Receptor xsd:string{}[])property_value( P204 Protein_Has_Biochemical_Function|G Protein-Coupled Receptor xsd:string{}[])def( GPR39 is a single-copy gene, expressed in brain and other peripheral tissues. It encodes G Protein-Coupled Receptor 39, which has high homology to the growth hormone secretagogue receptor (GHSR), a G protein-coupled receptor found in the pituitary gland and brain that is involved in the control of growth hormone release. The ligand-binding and functional properties of GPR39 remain to be determined. (from OMIM and Genomics 1997;46:426-34){{http://purl.obolibrary.org/obo/IAO_0000119=NCI} }[])is_a( C83479{}[]))
        at org.coode.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:79)
        at org.coode.owlapi.oboformat.OBOFormatStorer.storeOntology(OBOFormatStorer.java:74)
        at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.store(AbstractOWLOntologyStorer.java:182)
        at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.storeOntology(AbstractOWLOntologyStorer.java:126)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1001)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:438)
        ... 6 more
Caused by: org.obolibrary.oboformat.model.FrameStructureException: multiple def tags not allowed. in frame:Frame(C29670 id( C29670{}[])property_value( P106 Amino Acid, Peptide, or Protein xsd:string{}[])synonym( G Protein-Coupled Receptor 39 EXACT{{http://purl.obolibrary.org/obo/IAO_0000117=NCI} }[])property_value( code C29670 xsd:string{}[])property_value( P106 Receptor xsd:string{}[])name( G Protein-Coupled Receptor 39{}[])property_value( P204 Protein_Encoded_by_Gene|GPR39 Gene xsd:string{}[])property_value( P108 G Protein-Coupled Receptor 39 xsd:string{}[])synonym( Putative G Protein-Coupled Receptor GPR39 EXACT{{http://purl.obolibrary.org/obo/IAO_0000117=NCI} }[])property_value( P204 Protein_Has_Organism_Source|Human xsd:string{}[])synonym( GPR39 EXACT{{http://purl.obolibrary.org/obo/IAO_0000117=NCI} }[])property_value( P310 Retired_Concept xsd:string{}[])property_value( P102 AF034633 xsd:string{}[])is_obsolete( true{}[])def( Widely expressed by human GPR39 Gene (GPCR1 Family), 453-aa 51-kDa 7-transmembrane orphan G Protein-Coupled Receptor 39 exhibits high homology to the growth hormone secretagogue receptor (GHSR). (NCI){{http://purl.obolibrary.org/obo/IAO_0000119=NCI} }[])property_value( P203 Protein_Kind xsd:string{}[])property_value( P93 O43194 xsd:string{}[])property_value( P100 602886 xsd:string{}[])property_value( P204 Protein_Plays_Role_In_Biological_Process|G Protein-Coupled Receptor Signaling xsd:string{}[])property_value( P102 NM_001508 xsd:string{}[])property_value( P200 G Protein-Coupled Receptor xsd:string{}[])property_value( P204 Protein_Has_Biochemical_Function|G Protein-Coupled Receptor xsd:string{}[])def( GPR39 is a single-copy gene, expressed in brain and other peripheral tissues. It encodes G Protein-Coupled Receptor 39, which has high homology to the growth hormone secretagogue receptor (GHSR), a G protein-coupled receptor found in the pituitary gland and brain that is involved in the control of growth hormone release. The ligand-binding and functional properties of GPR39 remain to be determined. (from OMIM and Genomics 1997;46:426-34){{http://purl.obolibrary.org/obo/IAO_0000119=NCI} }[])is_a( C83479{}[]))
        at org.obolibrary.oboformat.model.Frame.checkMaxOneCardinality(Frame.java:383)
        at org.obolibrary.oboformat.model.Frame.check(Frame.java:357)
        at org.obolibrary.oboformat.model.OBODoc.check(OBODoc.java:344)
        at org.obolibrary.oboformat.writer.OBOFormatWriter.write(OBOFormatWriter.java:205)
        at org.coode.owlapi.oboformat.OBOFormatRenderer.render(OBOFormatRenderer.java:76)
        ... 11 more
```

**Comment by cmungall** [comment]
needs an ontologyIRI

Could file a ticket on the owlapi tracker (where this now lives) to either relax this or to make a more informative message.

We need the ontologyIRI anyway - I suggest reusing the original for now.

The next problem you will face is that owl->obo assumes obolib purls. I wish we had gone the configurable prefix route, but here we are. I have a box of hacks up my sleeve for this purpose (e.g. pre-convert to OBO purls, do the conversion, do the reverse if every converting back...)

**Comment by jamesaoverton** [comment]
I'm pretty sure the problem is that term C29670 has two definition annotations, and the OBOFormatWriter throws an exception rather than just a warning.

The two subsets convert to OBO format without complaint, but I don't know how good the results are.

**Comment by jamesaoverton** [comment]
I'm seeing 6 NCIt terms with multiple definitions. I'll filter them somehow.

**Comment by jamesaoverton** [comment]
I modified `convert.clj` to avoid writing multiple definitions, but it's really slowing things down.

Those 6 terms are all obsolete, so this is a lot of work for terms we probably don't care about.

**Comment by jamesaoverton** [comment]
Traded time for space to get reasonable performance for this check.

**Comment by jamesaoverton** [comment]
There are still lots of warnings about untranslated axioms, but I guess that's to be expected.

**Comment by cmungall** [comment]
correct

They are somewhat translated - they end up as functional syntax in the 
header
