### ISSUE TITLE
compilation/build issues

### ISSUE THREAD

**Issue by cmungall** [ontodev/ncit-obo#4]
curl behavior may vary between machines:

```
$ make
curl -Lko lib/robot.jar https://build.berkeleybop.org/job/robot/lastSuccessfulBuild/artifact/bin/robot.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file lib/robot.jar: No such file or directory
curl: (23) Failed writing body (0 != 15735)
make: *** [lib/robot.jar] Error 23 
```

easily fixed with a `mkdir`

not sure about this one:

```
$ make
lein uberjar
Compiling ncit-obo.align
java.lang.IllegalStateException: levenshtein already refers to: #'clj-fuzzy.metrics/levenshtein in namespace: ncit-obo.align, compiling:(ncit_obo/align.clj:162:1)
Exception in thread "main" java.lang.IllegalStateException: levenshtein already refers to: #'clj-fuzzy.metrics/levenshtein in namespace: ncit-obo.align, compiling:(ncit_obo/align.clj:162:1)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6730)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.analyze(Compiler.java:6485)
        at clojure.lang.Compiler.compile1(Compiler.java:7318)
        at clojure.lang.Compiler.compile(Compiler.java:7390)
        at clojure.lang.RT.compile(RT.java:399)
        at clojure.lang.RT.load(RT.java:444)
        at clojure.lang.RT.load(RT.java:412)
        at clojure.core$load$fn__5448.invoke(core.clj:5866)
        at clojure.core$load.doInvoke(core.clj:5865)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5671)
        at clojure.core$compile$fn__5453.invoke(core.clj:5877)
        at clojure.core$compile.invoke(core.clj:5876)
        at user$eval9$fn__18.invoke(form-init4647216934609444215.clj:1)
        at user$eval9.invoke(form-init4647216934609444215.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6782)
        at clojure.lang.Compiler.eval(Compiler.java:6772)
        at clojure.lang.Compiler.load(Compiler.java:7227)
        at clojure.lang.Compiler.loadFile(Compiler.java:7165)
        at clojure.main$load_script.invoke(main.clj:275)
        at clojure.main$init_opt.invoke(main.clj:280)
        at clojure.main$initialize.invoke(main.clj:308)
        at clojure.main$null_opt.invoke(main.clj:343)
        at clojure.main$main.doInvoke(main.clj:421)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalStateException: levenshtein already refers to: #'clj-fuzzy.metrics/levenshtein in namespace: ncit-obo.align
        at clojure.lang.Namespace.warnOrFailOnReplace(Namespace.java:88)
        at clojure.lang.Namespace.intern(Namespace.java:72)
        at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:534)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
        ... 29 more
Compilation failed: Subprocess failed
make: *** [target/uberjar/ncit-obo-0.1.0-SNAPSHOT-standalone.jar] Error 1
```

**Comment by jamesaoverton** [comment]
Should be fixed by 47cbb6bd641ed5328677c1d5ef21935f1b2aeb86.
